name: ci workflow for python app test
on:
  push:
    branches:
      - "main"
# creating jobs 
jobs:
  ashu-python-app-test:
    runs-on: ubuntu-latest
    steps:
      - name: checking python version on platform 
        run: python -V 
